### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by jizongFox** [WeiWangTrento/Recurrent-U-Net#1]
Hi @WeiWangTrento 
Very interesting work. I want to know when the code would be available?

**Comment by WeiWangTrento** [comment]
Thank you for your interest. Just finished CVPR. I will clean the code asap and hopefully it can be uploaded around the Christmas time.

Cheers,
Wei

**Comment by xiaoiker** [comment]
+1

**Comment by WeiWangTrento** [comment]
https://github.com/kcyu2014/recurrent-unet
