### ISSUE TITLE
Dataset can't unzip

### ISSUE THREAD

**Issue by huang-sien** [WeiWangTrento/Recurrent-U-Net#3]
Hi I got this problem. Somebody can help me? thanks.
![image](https://user-images.githubusercontent.com/51080043/109376191-e345e600-78fd-11eb-8036-a58086292934.png)

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by WeiWangTrento** [comment]
It is because the dataset is too large > 1GB.
I have uploaded it to google drive and updated the download link. It should work now.
